// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation.proto

/*
Package operation is a generated protocol buffer package.

It is generated from these files:
	operation.proto

It has these top-level messages:
	Operation
*/
package operation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// FileType detected from API
type Operation_FileType int32

const (
	Operation_JPEG Operation_FileType = 0
	Operation_PNG  Operation_FileType = 1
)

var Operation_FileType_name = map[int32]string{
	0: "JPEG",
	1: "PNG",
}
var Operation_FileType_value = map[string]int32{
	"JPEG": 0,
	"PNG":  1,
}

func (x Operation_FileType) String() string {
	return proto.EnumName(Operation_FileType_name, int32(x))
}
func (Operation_FileType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

//
// This Operation message descrie the operations to be done
// on file and bellow the example how to exploit it
//
// operation := &op.Operation{}
// operation.Id = 12
// operation.File = "hello.jpeg"
// operation.Type = op.Operation_JPEG
//
// out, err := proto.Marshal(operation)
// if err != nil {
// log.Fatalln("Failed to encode address book:", err)
// }
//
// fmt.Printf("ProtoBuf Example : %+v", out)
type Operation struct {
	Id      uint64               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	File    string               `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	Type    Operation_FileType   `protobuf:"varint,3,opt,name=type,enum=operation.Operation_FileType" json:"type,omitempty"`
	Command []*Operation_Command `protobuf:"bytes,4,rep,name=command" json:"command,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Operation) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Operation) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Operation) GetType() Operation_FileType {
	if m != nil {
		return m.Type
	}
	return Operation_JPEG
}

func (m *Operation) GetCommand() []*Operation_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

// Command to perform on the file
type Operation_Command struct {
	Command string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Flags   []string `protobuf:"bytes,2,rep,name=flags" json:"flags,omitempty"`
}

func (m *Operation_Command) Reset()                    { *m = Operation_Command{} }
func (m *Operation_Command) String() string            { return proto.CompactTextString(m) }
func (*Operation_Command) ProtoMessage()               {}
func (*Operation_Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Operation_Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Operation_Command) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func init() {
	proto.RegisterType((*Operation)(nil), "operation.Operation")
	proto.RegisterType((*Operation_Command)(nil), "operation.Operation.Command")
	proto.RegisterEnum("operation.Operation_FileType", Operation_FileType_name, Operation_FileType_value)
}

func init() { proto.RegisterFile("operation.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x7d, 0x61, 0xe4, 0xe2, 0xf4, 0x87, 0xf1, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x58, 0x82, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xd2, 0x32, 0x73, 0x52, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x43, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54,
	0x09, 0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x59, 0x3d, 0x84, 0xe1, 0x70, 0x73, 0xf4, 0xdc, 0x32,
	0x73, 0x52, 0x43, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0x4a, 0x85, 0xcc, 0xb8, 0xd8, 0x93, 0xf3, 0x73,
	0x73, 0x13, 0xf3, 0x52, 0x24, 0x58, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x64, 0xb0, 0xea, 0x72, 0x86,
	0xa8, 0x09, 0x82, 0x29, 0x96, 0xb2, 0xe4, 0x62, 0x87, 0x8a, 0x09, 0x49, 0x20, 0x8c, 0x60, 0x04,
	0x3b, 0x06, 0xc6, 0x15, 0x12, 0xe1, 0x62, 0x4d, 0xcb, 0x49, 0x4c, 0x2f, 0x96, 0x60, 0x52, 0x60,
	0xd6, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x64, 0xb9, 0x38, 0x60, 0x8e, 0x10, 0xe2, 0xe0, 0x62, 0xf1,
	0x0a, 0x70, 0x75, 0x17, 0x60, 0x10, 0x62, 0xe7, 0x62, 0x0e, 0xf0, 0x73, 0x17, 0x60, 0x4c, 0x62,
	0x03, 0x07, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x61, 0xc2, 0x24, 0x61, 0x1b, 0x01, 0x00,
	0x00,
}
